/*
Para poner links
<marker name='marker_name'>texto con link</marker>

Para poner imagenes, tener en cuenta el tamaño de la foto
<img image='Imagen mas el formato jpg o paa' />

Para cambiar formatos y tamaño de las imagenes
https://image.online-convert.com/convert-to-jpg

Para cambiar la fuente y el color
<font color='#FF0000' size='15' face='tahomab'>Escribe texto aqui</font>

Para saltar a otra linea
<br/> 

Todos los colores:
http://www.w3schools.com/colors/colors_picker.asp

Tipos de fuente:
https://community.bistudio.com/wikidata/images/archive/0/0e/20140217182059%21Arma3Fonts.png

Importante no usar tildes porque el juego borrara esas letras
*/

/*player createDiaryRecord ["Diary",["Titulo de ejemplo",
"<font color='#FFFF00' size='19' face='tahomab'>Escribe aqui el texto</font><br/><font color='#FF0000' size='14' face='puristabold'>Escribe aquI el texto</font><br/><img image='foto.jpg' /> "]];
*/

player createDiaryRecord ["Diary",["Situacion Previa",
"
-FECHA:25/05/2026<br/><br/>
21:00 RADARES DE ALERTA TEMPRANA DETECTAN UN OBJETO VOLANDO A 7000 METROS DE ALTURA A UNA VELOCIDAD DE MACH 4 SOBRE LA FRONTERA CHINO-TAKISTANI.<br/>
21:07 EL OBJETO DESCIENDE BRUSCAMENTE Y SE CREE QUE SE HA ESTRELLADO EN ALGUN LUGAR DE LA REGIÓN DE TAYIKISTAN.<br/>
21:35 UN SATÉLITE SE POSICIONA PARA OBTENER IMAGENES DE LA ZONA.<br/>
21:37 EL SATÉLITE NO LOGRA CAPTAR IMAGENES DEBIDO A POTENTES INTERFERENCIAS ELECTROMAGNETICAS.<br/>
22:40 LAS FUERZAS LOCALES TRATAN DE LLEGAR AL OBJETIVO PERO LOS INSURGENTES LES OBLIGAN A RETIRARSE, NUMERO DE BAJAS 69.<br/>
23:39 TODAS LAS COMUNICACIONES DEPENDIENTES DE SATELITE SE VEN AFECTADAS POR LAS INTERFERENCIAS.<br/>
OPERACION “A CIEGAS” ES AUTORIZADA.<br/>
"]];

player createDiaryRecord ["Diary",["Informe: ",
"UN PEQUENHO EQUIPO DE ASALTO SERA INFILTRADO EN UN VEHICULO EN LA ZONA DE OPERACIONES (DEBIDO A LA DELICADEZ DE LA MISION ESTOS NO PODRAN LLEVAR NADA QUE LOS VINCULE CON *******) DONDE LOCALIZARAN EL OBJETO NOMBRE EN CLAVE “BLACK SHARK”. 
UNA VEZ LOCALIZADO EL OBJETIVO SERA ASEGURADO Y SE ESPERARA A EL PROTOTIPO ********* PARA SU EXTRACCION. EN CASO DE NO SER POSIBLE DEBERAN TOMARSE IMAGENES DEL OBJETIVO Y PROCEDER A SU ELIMINACION.<br/>
DADA LA SITUACION EL EQUIPO NO CONTARA CON NINGUN APOYO Y MANTENDRA SILENCIO DE RADIO HASTA LA LLEGADA A LOS PUNTOS DESIGNADOS, UNA VEZ EL OBJETIVO HAYA SIDO ASEGURADO O DESTRUIDO EL EQUIPO DEBERA MOVERSE A LA BASE AEREA ABANDONADA AL OESTE DE RASMAN DONDE UN AC-130 RECOGERA AL EQUIPO Y A SU VEHICULO.

"]];

player createDiaryRecord ["Diary",["Palabras clave: ",
"ROMEO: INICIO DE OPERACION (TODOS ABORDAN EL VEHICULO)<br/>
PAPA: LOCALIZAMOS SEÑAL DEL OBJETIVO<br/>
OPACHKI: OBJETIVO LOCALIZADO<br/>
BRAVO: OBJETIVO ASEGURADO Y LISTO PARA EXTRACCION <br/>
DELTA: OBJETIVO NEUTRALIZADO<br/>
AGUA MOJADA: LLEGADA A EXTRACCION<br/>
NOMAD: EXTRACCION CANCELADA Y SE PROCEDE A EXTRACCIÓN ALTERNATIVA<br/>
LA EXTRACCIÓN ALTERNATIVA SERA MEDIANTE LA BASE SITUADA EN EL SUR, DONDE ENLAZARA CON TROPAS ALIADAS Y ESTAS FACILITARAN SU EXTRACCION.<br/>


"]];

player createDiaryRecord ["Diary",["Protocolo: ",
"
AUTORIZADA ELIMINACION DE TODOS LOS TESTIGOS<br/>


POSIBLES AMENAZAS:<br/>
INSURGENTES: LOCALES EXTREMISTAS EQUIPADOS CON ANTIGUO EQUIPAMIENTO SOVIETICO Y AMERICANO REMINISCENTES DE LA GUERRA RUSO-AFGANA <br/>


*****: LOS PRINCIPALES SOSPECHOSOS DE SER PROPIETARIOS DEL OBJETIVO SON ***** Y ***** LOS CUALES SEGURAMENTE QUIERAN RECUPERARLO LO ANTES POSIBLE.<br/>

EQUIPAMIENTO ESPECIAL:<br/>

EL EQUIPO SE PODRÁ ENCONTRAR EN CAJAS DEL PISO FRANCO.<br/>

LOS OPERATIVOS SERAN EQUIPADOS CON UN ESCANER DE FRECUENCIAS EL CUAL LES PERMITIRA LOCALIZAR AL OBJETIVO (ESTE OBJETO ES ALTO SECRETO POR LO QUE NO DEBE SER PERDIDO BAJO NINGUN CONCEPTO).<br/>

SE LES PROPORCIONARA UN VEHICULO QUE LES PERMITA MOVERSE POR EL ESCARPADO TERRENO DE LA ZO.<br/>

SE RECOMIENDA EL EMPLEO DE MUNICION LOCAL PARA MINIMIZAR LAS PRUEBAS Y PERMITIR EL REARME EN ENEMIGOS ABATIDOS.<br/>
"]];